using System;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Markup;
using System.Windows.Media;

namespace OpenCodexLauncherV2
{
    public static class ModernTheme
    {
        public static readonly Brush Accent = new SolidColorBrush(Color.FromRgb(82,105,158));
        public static void Apply(Window window)
        {
            if (Application.Current != null && !Application.Current.Resources.Contains("ModernTheme"))
            {
                var dictionary = (ResourceDictionary)XamlReader.Parse(Resources);
                Application.Current.Resources.MergedDictionaries.Add(dictionary);
                Application.Current.Resources["ModernTheme"] = true;
            }
            window.FontFamily = new FontFamily("DengXian, Segoe UI");
            window.FontSize = 14; window.FontWeight = FontWeights.SemiBold; window.UseLayoutRounding = true; window.Background = Brushes.White;
        }
        public static void Primary(Button button) { button.Background=Accent; button.Foreground=Brushes.White; button.BorderBrush=Accent; }
        const string Resources = @"<ResourceDictionary xmlns='http://schemas.microsoft.com/winfx/2006/xaml/presentation' xmlns:x='http://schemas.microsoft.com/winfx/2006/xaml'>
<Style TargetType='Window'><Setter Property='FontFamily' Value='DengXian, Segoe UI'/><Setter Property='FontSize' Value='14'/><Setter Property='FontWeight' Value='SemiBold'/><Setter Property='Background' Value='#F6F7F9'/></Style>
<Style TargetType='Button'>
 <Setter Property='Background' Value='White'/><Setter Property='Foreground' Value='#263044'/><Setter Property='BorderBrush' Value='#DFE3EB'/><Setter Property='BorderThickness' Value='1'/><Setter Property='Padding' Value='16,10'/><Setter Property='MinHeight' Value='38'/><Setter Property='Cursor' Value='Hand'/>
 <Setter Property='Template'><Setter.Value><ControlTemplate TargetType='Button'><Border x:Name='surface' CornerRadius='8' Background='{TemplateBinding Background}' BorderBrush='{TemplateBinding BorderBrush}' BorderThickness='{TemplateBinding BorderThickness}' Padding='{TemplateBinding Padding}'><ContentPresenter HorizontalAlignment='{TemplateBinding HorizontalContentAlignment}' VerticalAlignment='Center' RecognizesAccessKey='True'/></Border><ControlTemplate.Triggers><Trigger Property='IsMouseOver' Value='True'><Setter TargetName='surface' Property='Opacity' Value='0.82'/></Trigger><Trigger Property='IsPressed' Value='True'><Setter TargetName='surface' Property='Opacity' Value='0.65'/></Trigger><Trigger Property='IsKeyboardFocused' Value='True'><Setter TargetName='surface' Property='BorderBrush' Value='#52699E'/><Setter TargetName='surface' Property='BorderThickness' Value='2'/></Trigger><Trigger Property='IsEnabled' Value='False'><Setter Property='Opacity' Value='0.45'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter>
</Style>
<Style TargetType='TextBox'><Setter Property='Background' Value='White'/><Setter Property='Foreground' Value='#263044'/><Setter Property='BorderBrush' Value='#DFE3EB'/><Setter Property='BorderThickness' Value='1'/><Setter Property='Padding' Value='10,8'/><Setter Property='VerticalContentAlignment' Value='Center'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='TextBox'><Border x:Name='surface' CornerRadius='7' Background='{TemplateBinding Background}' BorderBrush='{TemplateBinding BorderBrush}' BorderThickness='{TemplateBinding BorderThickness}'><ScrollViewer x:Name='PART_ContentHost' Focusable='False' Padding='{TemplateBinding Padding}'/></Border><ControlTemplate.Triggers><Trigger Property='IsKeyboardFocusWithin' Value='True'><Setter TargetName='surface' Property='BorderBrush' Value='#52699E'/></Trigger><Trigger Property='IsEnabled' Value='False'><Setter Property='Opacity' Value='0.5'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='PasswordBox'><Setter Property='Background' Value='White'/><Setter Property='BorderBrush' Value='#DFE3EB'/><Setter Property='BorderThickness' Value='1'/><Setter Property='Padding' Value='10,8'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='PasswordBox'><Border x:Name='surface' CornerRadius='7' Background='{TemplateBinding Background}' BorderBrush='{TemplateBinding BorderBrush}' BorderThickness='{TemplateBinding BorderThickness}'><ScrollViewer x:Name='PART_ContentHost' Focusable='False' Padding='{TemplateBinding Padding}'/></Border><ControlTemplate.Triggers><Trigger Property='IsKeyboardFocusWithin' Value='True'><Setter TargetName='surface' Property='BorderBrush' Value='#52699E'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='ComboBox'><Setter Property='Background' Value='White'/><Setter Property='BorderBrush' Value='#DFE3EB'/><Setter Property='BorderThickness' Value='1'/><Setter Property='MinHeight' Value='38'/><Setter Property='Padding' Value='10,8'/><Setter Property='ScrollViewer.HorizontalScrollBarVisibility' Value='Disabled'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='ComboBox'><Grid><Border x:Name='comboSurface' Background='{TemplateBinding Background}' BorderBrush='{TemplateBinding BorderBrush}' BorderThickness='1' CornerRadius='7'/><ToggleButton Focusable='False' IsChecked='{Binding IsDropDownOpen,RelativeSource={RelativeSource TemplatedParent},Mode=TwoWay}' Background='Transparent' BorderThickness='0'><ToggleButton.Template><ControlTemplate TargetType='ToggleButton'><Border Background='Transparent'><TextBlock Text='⌄' HorizontalAlignment='Right' VerticalAlignment='Center' Margin='0,0,12,0' Foreground='#6C778C'/></Border></ControlTemplate></ToggleButton.Template></ToggleButton><ContentPresenter x:Name='selected' Content='{TemplateBinding SelectionBoxItem}' ContentTemplate='{TemplateBinding SelectionBoxItemTemplate}' ContentTemplateSelector='{TemplateBinding ItemTemplateSelector}' ContentStringFormat='{TemplateBinding SelectionBoxItemStringFormat}' Margin='10,6,32,6' VerticalAlignment='Center' IsHitTestVisible='False'/><TextBox x:Name='PART_EditableTextBox' Margin='1,1,30,1' Visibility='Hidden' Background='Transparent' BorderThickness='0'/><Popup x:Name='PART_Popup' Placement='Bottom' IsOpen='{TemplateBinding IsDropDownOpen}' AllowsTransparency='True' Focusable='False' PopupAnimation='Fade'><Border Background='White' BorderBrush='#DFE3EB' BorderThickness='1' CornerRadius='8' Padding='4' MinWidth='{Binding ActualWidth,RelativeSource={RelativeSource TemplatedParent}}' MaxHeight='320'><ScrollViewer CanContentScroll='True'><ItemsPresenter/></ScrollViewer></Border></Popup></Grid><ControlTemplate.Triggers><Trigger Property='IsKeyboardFocusWithin' Value='True'><Setter TargetName='comboSurface' Property='BorderBrush' Value='#52699E'/><Setter TargetName='comboSurface' Property='BorderThickness' Value='2'/></Trigger><Trigger Property='IsEditable' Value='True'><Setter TargetName='selected' Property='Visibility' Value='Hidden'/><Setter TargetName='PART_EditableTextBox' Property='Visibility' Value='Visible'/></Trigger><Trigger Property='IsEnabled' Value='False'><Setter Property='Opacity' Value='0.5'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='ComboBoxItem'><Setter Property='Padding' Value='10,8'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='ComboBoxItem'><Border x:Name='surface' CornerRadius='5' Padding='{TemplateBinding Padding}' Background='Transparent'><ContentPresenter/></Border><ControlTemplate.Triggers><Trigger Property='IsHighlighted' Value='True'><Setter TargetName='surface' Property='Background' Value='#EDF1F8'/></Trigger><Trigger Property='IsSelected' Value='True'><Setter Property='Foreground' Value='#52699E'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='CheckBox'><Setter Property='VerticalContentAlignment' Value='Center'/><Setter Property='Margin' Value='0,4'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='CheckBox'><Grid Background='Transparent'><Grid.ColumnDefinitions><ColumnDefinition Width='24'/><ColumnDefinition Width='*'/></Grid.ColumnDefinitions><Border x:Name='box' Width='17' Height='17' CornerRadius='4' BorderBrush='#B5BECE' BorderThickness='1' Background='White'><TextBlock x:Name='tick' Text='✓' Foreground='White' Visibility='Collapsed' HorizontalAlignment='Center' VerticalAlignment='Center' FontSize='12'/></Border><ContentPresenter Grid.Column='1' Margin='6,0,0,0' VerticalAlignment='Center' RecognizesAccessKey='True'/></Grid><ControlTemplate.Triggers><Trigger Property='IsChecked' Value='True'><Setter TargetName='box' Property='Background' Value='#52699E'/><Setter TargetName='box' Property='BorderBrush' Value='#52699E'/><Setter TargetName='tick' Property='Visibility' Value='Visible'/></Trigger><Trigger Property='IsKeyboardFocused' Value='True'><Setter TargetName='box' Property='BorderBrush' Value='#263044'/><Setter TargetName='box' Property='BorderThickness' Value='2'/></Trigger><Trigger Property='IsEnabled' Value='False'><Setter Property='Opacity' Value='0.45'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='ListBoxItem'><Setter Property='Padding' Value='10,8'/><Setter Property='HorizontalContentAlignment' Value='Stretch'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='ListBoxItem'><Border x:Name='surface' CornerRadius='7' Padding='{TemplateBinding Padding}' Background='{TemplateBinding Background}' BorderBrush='Transparent' BorderThickness='1'><ContentPresenter/></Border><ControlTemplate.Triggers><Trigger Property='IsMouseOver' Value='True'><Setter TargetName='surface' Property='Background' Value='#F1F3F7'/></Trigger><Trigger Property='IsKeyboardFocusWithin' Value='True'><Setter TargetName='surface' Property='BorderBrush' Value='#52699E'/></Trigger><Trigger Property='IsSelected' Value='True'><Setter TargetName='surface' Property='Background' Value='#E9EEF7'/><Setter Property='Foreground' Value='#405984'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
<Style TargetType='ScrollBar'><Setter Property='Width' Value='10'/><Setter Property='Template'><Setter.Value><ControlTemplate TargetType='ScrollBar'><Grid Background='Transparent'><Track x:Name='PART_Track' IsDirectionReversed='True'><Track.DecreaseRepeatButton><RepeatButton Command='ScrollBar.PageUpCommand' Opacity='0' Focusable='False'/></Track.DecreaseRepeatButton><Track.Thumb><Thumb><Thumb.Template><ControlTemplate TargetType='Thumb'><Border CornerRadius='4' Background='#C9D0DC' Margin='2'/></ControlTemplate></Thumb.Template></Thumb></Track.Thumb><Track.IncreaseRepeatButton><RepeatButton Command='ScrollBar.PageDownCommand' Opacity='0' Focusable='False'/></Track.IncreaseRepeatButton></Track></Grid><ControlTemplate.Triggers><Trigger Property='Orientation' Value='Horizontal'><Setter Property='Width' Value='Auto'/><Setter Property='Height' Value='10'/><Setter TargetName='PART_Track' Property='IsDirectionReversed' Value='False'/></Trigger></ControlTemplate.Triggers></ControlTemplate></Setter.Value></Setter></Style>
</ResourceDictionary>";
    }
}
